use UNIVER;

--1 независимый
SELECT FACULTY.FACULTY,PROFESSION.PROFESSION_NAME,PULPIT.PULPIT
FROM PULPIT,FACULTY,PROFESSION
WHERE PULPIT.FACULTY = FACULTY.FACULTY and FACULTY.FACULTY = PROFESSION.FACULTY and PROFESSION_NAME in (SELECT PROFESSION_NAME FROM PROFESSION 
where(PROFESSION_NAME LIKE '%технологи%'))

--2 независимый
SELECT FACULTY.FACULTY,PROFESSION.PROFESSION_NAME,PULPIT.PULPIT
FROM PULPIT inner join FACULTY on PULPIT.FACULTY = FACULTY.FACULTY inner join PROFESSION on FACULTY.FACULTY = PROFESSION.FACULTY
WHERE PROFESSION_NAME in (SELECT PROFESSION_NAME FROM PROFESSION 
where(PROFESSION_NAME LIKE '%технологи%'))

--3 
SELECT FACULTY.FACULTY,PROFESSION.PROFESSION_NAME,PULPIT.PULPIT
FROM PULPIT inner join FACULTY on PULPIT.FACULTY = FACULTY.FACULTY inner join PROFESSION on FACULTY.FACULTY = PROFESSION.FACULTY
WHERE(PROFESSION_NAME LIKE '%технологи%')

--4 коррелируемый
SELECT AUDITORIUM.AUDITORIUM_NAME, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME, AUDITORIUM.AUDITORIUM_CAPACITY
FROM AUDITORIUM, AUDITORIUM_TYPE
WHERE AUDITORIUM = 
(select top(1) AUDITORIUM from AUDITORIUM where AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE order by AUDITORIUM_CAPACITY desc)

--5 коррелируемый
SELECT FACULTY.FACULTY
FROM FACULTY
WHERE not exists(SELECT PULPIT FROM PULPIT WHERE FACULTY.FACULTY = PULPIT.FACULTY)

--6 независимые
SELECT top(1)
(SELECT avg(NOTE) from PROGRESS
WHERE PROGRESS.SUBJECT like 'ОАиП')[ОАиП],
(SELECT avg(NOTE) from PROGRESS
WHERE PROGRESS.SUBJECT like 'БД')[БД],
(SELECT avg(NOTE) from PROGRESS
WHERE PROGRESS.SUBJECT like 'СУБД')[СУБД]	
FROM PROGRESS

--7 независимый
SELECT NOTE, SUBJECT 
from PROGRESS
WHERE NOTE >=all(select NOTE from PROGRESS where SUBJECT like '%СУБД')

--8 независимый
SELECT NOTE, SUBJECT 
from PROGRESS
WHERE NOTE >=any(select NOTE from PROGRESS where SUBJECT like 'ОАиП')
