use UNIVER;

--ИДиП потому что нет ТОВ
--1
	SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)[Средняя оценка]
	FROM FACULTY inner join GROUPS on FACULTY.FACULTY = GROUPS.FACULTY inner join STUDENT on GROUPS.IDGROUP = STUDENT.IDGROUP inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
	WHERE FACULTY.FACULTY in ('ИДиП')
	GROUP BY ROLLUP (FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT)

--2
SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)[Средняя оценка]
FROM FACULTY inner join GROUPS on FACULTY.FACULTY = GROUPS.FACULTY inner join STUDENT on GROUPS.IDGROUP = STUDENT.IDGROUP inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY in ('ИДиП')
GROUP BY CUBE (FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT)

--3
SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)[Средняя оценка]
FROM FACULTY inner join GROUPS on FACULTY.FACULTY = GROUPS.FACULTY inner join STUDENT on GROUPS.IDGROUP = STUDENT.IDGROUP inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY in ('ИДиП')
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT
union
SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)[Средняя оценка]
FROM FACULTY inner join GROUPS on FACULTY.FACULTY = GROUPS.FACULTY inner join STUDENT on GROUPS.IDGROUP = STUDENT.IDGROUP inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY in ('ХТиТ')
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT
union
SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)[Средняя оценка]
FROM FACULTY inner join GROUPS on FACULTY.FACULTY = GROUPS.FACULTY inner join STUDENT on GROUPS.IDGROUP = STUDENT.IDGROUP inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY in ('ИДиП')
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT

SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)[Средняя оценка]
FROM FACULTY inner join GROUPS on FACULTY.FACULTY = GROUPS.FACULTY inner join STUDENT on GROUPS.IDGROUP = STUDENT.IDGROUP inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY in ('ИДиП')
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT
union all
SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)[Средняя оценка]
FROM FACULTY inner join GROUPS on FACULTY.FACULTY = GROUPS.FACULTY inner join STUDENT on GROUPS.IDGROUP = STUDENT.IDGROUP inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY in ('ХТиТ')
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT
union all
SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)[Средняя оценка]
FROM FACULTY inner join GROUPS on FACULTY.FACULTY = GROUPS.FACULTY inner join STUDENT on GROUPS.IDGROUP = STUDENT.IDGROUP inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY in ('ИДиП')
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT

--4
SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)[Средняя оценка]
FROM FACULTY inner join GROUPS on FACULTY.FACULTY = GROUPS.FACULTY inner join STUDENT on GROUPS.IDGROUP = STUDENT.IDGROUP inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY in ('ИДиП')
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT
intersect
SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)[Средняя оценка]
FROM FACULTY inner join GROUPS on FACULTY.FACULTY = GROUPS.FACULTY inner join STUDENT on GROUPS.IDGROUP = STUDENT.IDGROUP inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY in ('ХТиТ')
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT

--5
SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)[Средняя оценка]
FROM FACULTY inner join GROUPS on FACULTY.FACULTY = GROUPS.FACULTY inner join STUDENT on GROUPS.IDGROUP = STUDENT.IDGROUP inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY in ('ИДиП')
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT
except
SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,AVG(PROGRESS.NOTE)[Средняя оценка]
FROM FACULTY inner join GROUPS on FACULTY.FACULTY = GROUPS.FACULTY inner join STUDENT on GROUPS.IDGROUP = STUDENT.IDGROUP inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY in ('ХТиТ')
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT