use UNIVER;

--1 
SELECT AUDITORIUM_TYPE.AUDITORIUM_TYPENAME,max(AUDITORIUM_CAPACITY)[Максимальная вместимость],min(AUDITORIUM_CAPACITY)[Минимальная вместимость],avg(AUDITORIUM_CAPACITY)[Средняя вместимость], count(*)[Общее кол-во], sum(AUDITORIUM_CAPACITY)[Суммарная вместимость]
FROM AUDITORIUM inner join AUDITORIUM_TYPE on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
GROUP BY AUDITORIUM_TYPE.AUDITORIUM_TYPENAME

--2
--Такое же как первое

--3
SELECT *
FROM(SELECT CASE 
when PROGRESS.NOTE between 4 and 5 then '4-5'
when PROGRESS.NOTE between 6 and 7 then '6-7'
when PROGRESS.NOTE between 8 and 9 then '8-9'
when PROGRESS.NOTE = 10 then '10'
else 'Неправильные данные'
end[Оценки],COUNT(*)[Количество]
FROM PROGRESS GROUP BY CASE
when PROGRESS.NOTE between 4 and 5 then '4-5'
when PROGRESS.NOTE between 6 and 7 then '6-7'
when PROGRESS.NOTE between 8 and 9 then '8-9'
when PROGRESS.NOTE = 10 then '10'
else 'Неправильные данные'
end) as T
ORDER BY CASE [Оценки]
when '4-5' then 4
when '6-7' then 3
when '8-9' then 2
when '10' then 1
else 0
end

--4
SELECT FACULTY.FACULTY[Факультет], GROUPS.PROFESSION[специальность], GROUPS.COURSE[Курс],round(avg(cast(PROGRESS.NOTE as float(4))),2)[средняя оценка]
FROM FACULTY inner join GROUPS on FACULTY.FACULTY = GROUPS.FACULTY inner join STUDENT on GROUPS.IDGROUP = STUDENT.IDGROUP inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,GROUPS.COURSE

--5
SELECT FACULTY.FACULTY[Факультет], GROUPS.PROFESSION[специальность], GROUPS.COURSE[Курс],round(avg(cast(PROGRESS.NOTE as float(4))),2)[средняя оценка]
FROM FACULTY inner join GROUPS on FACULTY.FACULTY = GROUPS.FACULTY inner join STUDENT on GROUPS.IDGROUP = STUDENT.IDGROUP inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
where PROGRESS.SUBJECT in ('БД','ОАиП')
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,GROUPS.COURSE

--6 (поменял на ИДиП потому что на ТОВ нет оценок)
SELECT FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT,round(avg(cast(PROGRESS.NOTE as float(4))),2)[средняя оценка]
FROM FACULTY inner join GROUPS on FACULTY.FACULTY = GROUPS.FACULTY inner join STUDENT on GROUPS.IDGROUP = STUDENT.IDGROUP inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY in ('ИДиП')
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION,PROGRESS.SUBJECT

--7
SELECT SUBJECT.SUBJECT, PROGRESS.NOTE, (SELECT COUNT(PROGRESS.IDSTUDENT) from PROGRESS where SUBJECT.SUBJECT = PROGRESS.SUBJECT)[Кол-во студентов]
FROM SUBJECT,PROGRESS
GROUP BY SUBJECT.SUBJECT,PROGRESS.NOTE
HAVING PROGRESS.NOTE = 8 or PROGRESS.NOTE = 9



